# Copyright 2022-Present Couchbase, Inc.
#
# Use of this software is governed by the Business Source License included in
# the file licenses/BSL-Couchbase.txt.  As of the Change Date specified in that
# file, in accordance with the Business Source License, use of this software
# will be governed by the Apache License, Version 2.0, included in the file
# licenses/APL2.txt.

name: openapi

on:
  push:
    # Only run when we change an API spec
    paths:
      - 'docs/api/**'
    branches:
      - 'master'
      - 'release/*'
      - 'CBG*'
      - 'ci-*'
      - 'api-ci-*'
  pull_request:
    # Only run when we change an API spec
    paths:
      - 'docs/api/**'
    branches:
      - 'master'
      - 'release/*'

jobs:
  api_validation:
    runs-on: ubuntu-latest
    name: OpenAPI Validation
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: r7kamura/redocly-problem-matchers@a0539e4b48dbffad0c5bd57ae989a40d78c8ab5d # v1.0.0
      - uses: mhiew/redoc-lint-github-action@fa9aaf1f917397c43201196d45b2cb5d95dcbf86 # v3
        with:
          args: '--format stylish'
        env:
          NO_COLOR: '1'

  yamllint:
    name: 'yamllint'
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - uses: actions/checkout@f43a0e5ff2bd294095638e18286ca9a3d1956744 # v3.6.0
      - uses: karancode/yamllint-github-action@0a904064817924fc6fb449a32f67f25bfacc48ae # master
