---
name: yamllint
on:
  push:
    # Only run when we change an API spec
    paths:
      - '**.yml'
      - '**.yaml'
    branches:
      - 'master'
      - 'release/*'
      - 'CBG*'
      - 'ci-*'
      - 'api-ci-*'
  pull_request:
    # Only run when we change an API spec
    paths:
      - '**.yaml'
    branches:
      - 'master'
      - 'release/*'
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yaml-lint
        uses: ibiqlik/action-yamllint@v3
